version: '3.9'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: 'minio'
      MINIO_ROOT_PASSWORD: 'Secret1!'
      MINIO_ADDRESS: ':1900'
      MINIO_CONSOLE_ADDRESS: ':1901'
    command: minio server /data
    ports:
      - "1900:1900"
      - "1901:1901"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - external-net
networks:
  external-net:
    name: external-net
    external: true
